<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-3PBEUFOV" failures="1" tests="2" name="Test(failed)" time="0.078" errors="0" timestamp="2022-01-01T06:53:52 IST">
  <testcase classname="testngdisscussion.SoftAssertDisc" name="testCase1" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at testngdisscussion.SoftAssertDisc.testCase1(SoftAssertDisc.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="testngdisscussion.TestCasesForFailedEcecution" name="loginTest" time="0.0">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="testngdisscussion.TestCasesForFailedEcecution" name="a" time="0.0">
    <ignored/>
  </testcase> <!-- a -->
  <testcase classname="testngdisscussion.TestCasesForFailedEcecution" name="home" time="0.0">
    <ignored/>
  </testcase> <!-- home -->
  <testcase classname="testngdisscussion.SoftAssertDisc" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test(failed) -->
